# Generated by Django 3.0.6 on 2020-07-16 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='images/profile_pics/%Y/%m/%d')),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(choices=[('CEO', 'Chief Executive Office'), ('PM', 'Production Manager'), ('CTO', 'CTO'), ('Acc', 'Accountant'), ('Member', 'Member')], max_length=50)),
                ('bio', models.TextField(max_length=1000)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CEO', 'Chief Executive Office'), ('PM', 'Production Manager'), ('CTO', 'CTO'), ('Acc', 'Accountant'), ('Member', 'Member')], max_length=100)),
                ('image', models.ImageField(default='images/committee/me.jpg', upload_to='images/committee')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('google', models.EmailField(blank=True, max_length=200, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
