# Generated by Django 3.0.6 on 2020-10-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200914_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/profile_pics/default.png', upload_to='images/profile_pics/%Y/%m/%d'),
        ),
    ]
