# Generated by Django 3.0.6 on 2020-10-21 17:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201021_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
    ]
