# Generated by Django 3.0.6 on 2020-05-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0002_auto_20200528_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/AboutUs')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('connected_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainbiz.About')),
            ],
        ),
    ]
