# Generated by Django 3.0.6 on 2020-05-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0003_about_aboutusservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusservice',
            name='connected_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_service', to='mainbiz.About'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(default='fa fa-bar-chart', max_length=100),
        ),
    ]
