# Generated by Django 3.0.6 on 2020-06-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0005_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Sponsor',
        ),
    ]
