# Generated by Django 3.0.6 on 2020-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0006_auto_20200612_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.CharField(default='Member', max_length=50),
        ),
    ]
