# Generated by Django 3.0.6 on 2020-06-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0007_testimonial_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Gallery',
        ),
    ]
