# Generated by Django 3.0.6 on 2020-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0009_gallery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('text', models.TextField(max_length=50)),
                ('image1', models.ImageField(upload_to='images/intro')),
                ('image2', models.ImageField(upload_to='images/intro')),
                ('image3', models.ImageField(upload_to='images/intro')),
                ('image4', models.ImageField(upload_to='images/intro')),
                ('image5', models.ImageField(upload_to='images/intro')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
