# Generated by Django 3.0.6 on 2020-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0010_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='intro',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
