# Generated by Django 3.0.6 on 2020-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0011_auto_20200615_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
