# Generated by Django 3.0.6 on 2020-06-16 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0012_auto_20200615_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/entertainment/%Y/%m/%d')),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TechNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/technews/%Y/%m/%d')),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
