# Generated by Django 3.0.6 on 2020-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0013_auto_20200616_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
