# Generated by Django 3.0.6 on 2020-06-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0014_auto_20200616_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entertainment',
        ),
    ]
