# Generated by Django 3.0.6 on 2020-06-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainbiz', '0015_delete_entertainment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('music', 'music'), ('movie', 'movie'), ('gaming', 'gaming'), ('tech', 'tech'), ('events', 'events'), ('others', 'others')], max_length=50)),
                ('image', models.ImageField(upload_to='images/entertainment/%Y/%m/%d')),
                ('content', models.TextField()),
                ('text', tinymce.models.HTMLField(default='', null=True)),
                ('source', models.CharField(max_length=50)),
                ('source_link', models.URLField(default='#')),
                ('slug', models.SlugField(unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.DeleteModel(
            name='TechNew',
        ),
    ]
