# Generated by Django 3.0.6 on 2020-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0017_auto_20200623_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
