# Generated by Django 3.0.6 on 2020-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0027_auto_20201014_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='mainbiz.Tag'),
        ),
    ]
