# Generated by Django 3.0.6 on 2020-10-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbiz', '0029_auto_20201014_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mainbiz.Tag'),
        ),
    ]
